[workspace]

resolver = "2"

members = [ "1. Basics of Rust Concurrency/lifetime-mutexguard","1. Basics of Rust Concurrency/scoped-threads", "2. Atomics/progress-reporting-parking", "2. Atomics/stop-flag"]
